name: Countinuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Build the project
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: source/global.json
    - name: Build
      run: dotnet build source/

  # Run unit tests
  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: source/global.json
    - name: Test
      run: dotnet test source/

  # Check formatting
  lint:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: source/global.json
    - name: Lint style
      run: dotnet format style source/ --verify-no-changes
    - name: Lint analyzers
      run: dotnet format analyzers source/ --verify-no-changes --exclude Tests # Don't need to analyze the tests - these are supposed to test the application so any analyzer warnings don't matter that much
